### ISSUE TITLE
I must be doing something wrong?

### ISSUE THREAD

**Issue by akayer19** [johndhancock/prizepicks-to-csv#1]
Cloned your repo and extracted the folder.  Named it PrizePicks.  Added folder to VSC, and ran 'python scripts/scraper.py NFL'.  

$ python scripts/scraper.py NFL
  ---------------------       
  Searching for lines for {0}.
  ---------------------       
Traceback (most recent call last):
  File "C:\Users\Alex\Documents\PrizePicks\scripts\scraper.py", line 43, in <module>
    initial_request = requests.get('https://partner-api.prizepicks.com/projections', params=payload, header=HEADERS, timeout=30)
  File "C:\Users\Alex\AppData\Roaming\Python\Python310\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Alex\AppData\Roaming\Python\Python310\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: Session.request() got an unexpected keyword argument 'header'

What am I doing wrong?
Alex

**Comment by akayer19** [comment]
I re-downloaded the repository, via GitHub desktop, and opened with VSC.  I must have missed the files that were updated already commit. Works good!
