### ISSUE TITLE
Error during pp_data = initial_request.json() on scraper.py

### ISSUE THREAD

**Issue by akayer19** [johndhancock/prizepicks-to-csv#2]
Searching for lines for NBA
  ---------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Alex/Documents/DFS/scripts/scraper.py", line 50, in <module>
    pp_data = initial_request.json()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by akayer19** [comment]
scraper.py worked yesterday.  I see that there is a 404 error on https://partner-api.prizepicks.com/projections. Even when erasing to https://api.prizepicks.com/projections, looks like a json there, but same error.  What are your thoughts John?

**Comment by akayer19** [comment]
I updated requests module as well, to see if that was the issue.  It wasn't.

**Comment by akayer19** [comment]
Error I am getting is a 403, so PrizePicks doesn't like something.

**Comment by akayer19** [comment]
Got it!  Needed to change the 'user-agent': 'Chrome/109.0.0.0'.
